#!/bin/bash
# These commands will run the HPCCG executable on 1-64 processors at powers
# of 2 and change the problem size so that the same global problem is
# being solved regardless of processor count.  This is sometimes referred
# to as "strong scaling".

test -x "./test_HPCCG" || { echo "executable not found"; exit 1; }

mpirun -np 1 ./test_HPCCG 64 64 1024 | tee strongOut_01
mpirun -np 2 ./test_HPCCG 64 64 512  | tee strongOut_02
mpirun -np 4 ./test_HPCCG 64 64 256  | tee strongOut_04
mpirun -np 8 ./test_HPCCG 64 64 128  | tee strongOut_08
mpirun -np 16 ./test_HPCCG 64 64 64  | tee strongOut_16
mpirun -np 32 ./test_HPCCG 64 64 32  | tee strongOut_32
mpirun -np 64 ./test_HPCCG 64 64 16  | tee strongOut_64
